#!/bin/bash

cd "$(dirname "$0")" || exit

USAGE=$'Usage: audiollusion <name-of-illusion>
Illusions:
  binaural-beats
  octave-illusion
  shepard-tone'

case "$1" in
'' | -h | --help | help)
  echo >&2 "$USAGE"
  exit
  ;;
esac

if test -f ./src/"$1"; then
  ./src/"$1" "${@:2}"
else
  echo >&2 "Couldn't find audio illusion: $1"
  echo >&2 "$USAGE"
  exit 1
fi
